{
 "title": "EAP 7.4 Observability demo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "EAP 7.4 demo API stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total API hits",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "application_com_redhat_demo_eapobservabilty_EAPObservableService_greetInEnglishInvocations_total{}"
    }
   ]
  },
  {
   "title": "Total Hindi greetings API calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "application_com_redhat_demo_eapobservabilty_EAPObservableService_greetInHindiInvocations_total{}"
    }
   ]
  },
  {
   "title": "Total French greeting API calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "application_com_redhat_demo_eapobservabilty_EAPObservableService_greetInFrenchInvocations_total{}"
    }
   ]
  },
  {
   "title": "French greeting API call rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_com_redhat_demo_eapobservabilty_EAPObservableService_greetInFrenchDuration_one_min_rate_per_second{}"
    }
   ]
  },
  {
   "title": "Total English greeting API calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "application_com_redhat_demo_eapobservabilty_EAPObservableService_greetInEnglishInvocations_total{}"
    }
   ]
  },
  {
   "title": "Min response time for French greeting API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "application_com_redhat_demo_eapobservabilty_EAPObservableService_greetInFrenchDuration_min_seconds{}"
    }
   ]
  }
 ]
}