global:
  scrape_interval: 15s

  external_labels:
    monitor:'eap74-monitor'

scrape_configs:
  - job_name: 'eap74'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
    - targets: ['localhost:9990']

  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
